### ISSUE TITLE
Fix first click on an arrow

### ISSUE THREAD

**Issue by lukasz-gryzbon** [lsd-consulting/lsd-core#55]
When a diagram is loaded, the first click on any arrow in the diagram reloads the page.

The subsequent clicks don't do that.

Expected behaviour: no reloading triggered.

**Comment by nickmcdowall** [comment]
I wonder if this is only seen when an existing html report is changed and then clicked on after the file has been changed under-the-hood so to speak - i.e. for files that were not closed but have changed since they were last active. I don't seem to see this when a report is opened after being generated freshly but shout if you are seeing anything different?

**Comment by nickmcdowall** [comment]
Including link to related puml issue that Lukasz found: https://forum.plantuml.net/3402/links-embedded-other-html-will-open-embedded-inline-target

Also useful thread on the differences between _self and _top: https://stackoverflow.com/questions/18470097/difference-between-self-top-and-parent-in-the-anchor-tag-target-attribute

**Comment by nickmcdowall** [comment]
@lukasz-gryzbon the default behaviour of the links has been changed now - makes no difference when outside of an iframe so was happy to just make the change for improving the iframe experience. Should hopefully fix that issue you keep seeing once and for all 🤞
