### ISSUE TITLE
Store combined (and possibly individual) component diagram source in separate file(s)

### ISSUE THREAD

**Issue by lukasz-gryzbon** [lsd-consulting/lsd-core#64]
Having the source of the combined, as well as individual, component diagrams available for parsing and rendering outside LSD would be hugely useful.

For the combined source, I believe, all that is needed is a dump of all unique interactions - order should not be important.

**Comment by nickmcdowall** [comment]
Hey @lukasz-gryzbon,

Thinking about this and different approaches. A couple options that come to mind:

1. A component diagram per Report. For example every report may have multiple scenarios and each has its own component diagram currently but we could add an additional link at the top/bottom of the report for a component diagram taking into account all events from all the scenarios related to the report. So essentially this usually translates to a Test class having an overall component diagram for all test scenarios.
2. Additionally (or instead of) there could be a further component diagram that considers all Reports with all their scenarios - therefore if multiple tests are triggered then they all contribute towards an overall component diagram. One thought that springs to mind is that the index page could include a link to this overall component diagram file (or maybe displayed on the index page by default but a link sounds neater on reflection).

**Comment by lukasz-gryzbon** [comment]
These are all good ideas. I like both of them actually. The question is, should we implement any of them as part of this PR or create 2 new ones?
